/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDienChinh;


import QuanLyChiTietHoaDon.QuanLyChiTietHoaDonBUS;
import QuanLyChiTietHoaDon.ChiTietHoaDon;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class XemChiTietHoaDon extends javax.swing.JFrame {

    QuanLyChiTietHoaDonBUS qlcthd = new QuanLyChiTietHoaDonBUS();
    DefaultTableModel billDetailModel;
    
    /**
     * Creates new form ChiTietHoaDon
     */
    public XemChiTietHoaDon() {
        initComponents();
    }

    private static String toMoney(int d) {
        String s = String.valueOf(d);
        if (s.indexOf(".") != -1) {
            s = s.substring(0, s.indexOf("."));
        }

        return toMoney(s);
    }

    private static String toMoney(String s) {
        int odd = s.length() % 3;

        String s2 = s.substring(0, odd);

        int length = s.length() / 3;
        for (int i = 0; i < length; i++) {
            s2 += " " + s.substring(odd + i * 3, odd + i * 3 + 3);
        }

        return s2.trim() + "đ";
    }
    
    public void setBillDetailTable(String s){
        billDetailModel = (DefaultTableModel) billDetailTable.getModel();
        
        for(ChiTietHoaDon ct: qlcthd.dscthd){
            if(ct.getMaHD().equals(s)){
                billDetailModel.addRow(new Object[]{
                    ct.getMaHD() , ct.getMaSP() , ct.getSoLuong() , toMoney(ct.getDonGia()) , toMoney(ct.getThanhTien())
                });
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        billDetailTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        billDetailTable.setAutoCreateRowSorter(true);
        billDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HĐ", "Mã SP", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(billDetailTable);
        if (billDetailTable.getColumnModel().getColumnCount() > 0) {
            billDetailTable.getColumnModel().getColumn(0).setMinWidth(65);
            billDetailTable.getColumnModel().getColumn(0).setPreferredWidth(65);
            billDetailTable.getColumnModel().getColumn(0).setMaxWidth(65);
            billDetailTable.getColumnModel().getColumn(1).setMinWidth(65);
            billDetailTable.getColumnModel().getColumn(1).setPreferredWidth(65);
            billDetailTable.getColumnModel().getColumn(1).setMaxWidth(65);
            billDetailTable.getColumnModel().getColumn(2).setMinWidth(70);
            billDetailTable.getColumnModel().getColumn(2).setPreferredWidth(70);
            billDetailTable.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemChiTietHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billDetailTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
